### ISSUE TITLE
wrong translation for Contribute to this guide

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/experience-cloud-kcs.zh-Hant#1]
Issue in ./articles/KA-17481.md

[提供給本指南](https://experienceleague.adobe.com/docs/contributor/contributor-guide/introduction.html?lang=zh-Hant)

提供給本指南 seems to be a wrong translation (on every page)for [Contribute to this guide]

**Comment by adobechienan** [comment]
@yanlicao Thank you for your feedback. This is being reviewed and tracked in G11N-11038.

**Comment by adobechienan** [comment]
@yanlicao Thank you for your feedback. This is being reviewed and tracked in UGP-8020.

**Comment by yanlicao** [comment]
There has been no update for 5 months, but looks like this page is updated and problem seems to be fixed
I will close it from my end but please don't forget to follow up open issues
